import type { EndpointDefinition } from "./types";

export const endpoints = {
	XIT001: {
		id: "XIT001",
		methodName: "xit001",
		alias: "getRealEstatePrices",
		path: "/XIT001",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xit001/",
		category: "価格情報",
		nameJa: "不動産価格（取引価格・成約価格）情報取得API",
		summaryEn: "Get real estate transaction and contract price records.",
		kind: "json",
		requireOneOf: ["area", "city", "station"],
		params: [
			{ name: "priceClassification", inputName: "priceClassification", kind: "priceClassification", required: false, multiple: false, description: "価格情報区分コード" },
			{ name: "year", inputName: "year", kind: "year", required: true, multiple: false, description: "取引時期（年）" },
			{ name: "quarter", inputName: "quarter", kind: "quarter", required: false, multiple: false, description: "取引時期（四半期）" },
			{ name: "area", inputName: "area", kind: "prefectureCode", required: false, multiple: true, description: "都道府県コード" },
			{ name: "city", inputName: "city", kind: "cityCode", required: false, multiple: false, description: "市区町村コード" },
			{ name: "station", inputName: "station", kind: "stationCode", required: false, multiple: false, description: "駅コード" },
			{ name: "language", inputName: "language", kind: "language", required: false, multiple: false, description: "出力結果の言語" },
		],
		responseFields: [
			"Type",
			"Region",
			"MunicipalityCode",
			"Prefecture",
			"Municipality",
			"DistrictName",
			"TradePrice",
			"PricePerUnit",
			"FloorPlan",
			"Area",
			"UnitPrice",
			"LandShape",
			"Frontage",
			"TotalFloorArea",
			"BuildingYear",
			"Structure",
			"Use",
			"Purpose",
			"Direction",
			"Classification",
			"Breadth",
			"CityPlanning",
			"CoverageRatio",
			"FloorAreaRatio",
			"Period",
			"Renovation",
			"Remarks",
			"PriceCategory",
			"DistrictCode",
		],
	},
	XIT002: {
		id: "XIT002",
		methodName: "xit002",
		alias: "getMunicipalities",
		path: "/XIT002",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xit002/",
		category: "市区町村情報",
		nameJa: "都道府県内市区町村一覧取得API",
		summaryEn: "Get municipalities in a prefecture.",
		kind: "json",
		params: [
			{ name: "area", inputName: "area", kind: "prefectureCode", required: true, multiple: false, description: "都道府県コード" },
			{ name: "language", inputName: "language", kind: "language", required: false, multiple: false, description: "出力結果の言語" },
		],
		responseFields: [
			"id",
			"name",
			"name",
		],
	},
	XCT001: {
		id: "XCT001",
		methodName: "xct001",
		alias: "getAppraisalReports",
		path: "/XCT001",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xct001/",
		category: "価格情報",
		nameJa: "鑑定評価書情報API",
		summaryEn: "Get official land appraisal report records.",
		kind: "json",
		params: [
			{ name: "year", inputName: "year", kind: "year", required: true, multiple: false, description: "価格時点" },
			{ name: "area", inputName: "area", kind: "prefectureCode", required: true, multiple: true, description: "都道府県コード" },
			{ name: "division", inputName: "division", kind: "appraisalDivisionCode", required: true, multiple: false, description: "用途区分" },
		],
		responseFields: [
			"価格時点",
			"標準地番号 市区町村コード 県コード",
			"標準地番号 市区町村コード 市区町村コード",
			"標準地番号 地域名",
			"標準地番号 用途区分コード",
			"標準地番号 連番",
			"1㎡当たりの価格",
			"路線価 年",
			"路線価 相続税路線価",
			"路線価 倍率",
			"路線価 倍率種別",
			"標準地 所在地 所在地番",
			"標準地 所在地 住居表示",
			"標準地 所在地 仮換地番号",
			"標準地 地積 地積",
			"標準地 地積 内私道分",
			"標準地 形状 形状",
			"標準地 形状 形状比 間口",
			"標準地 形状 形状比 奥行",
			"標準地 形状 方位",
			"標準地 形状 平坦",
			"標準地 形状 傾斜度",
			"標準地 土地利用の現況 現況",
			"標準地 土地利用の現況 構造コード",
			"標準地 土地利用の現況 地上階数",
			"標準地 土地利用の現況 地下階数",
			"標準地 周辺の利用状況",
			"標準地 接面道路の状況 前面道路 方位",
			"標準地 接面道路の状況 前面道路 駅前区分",
			"標準地 接面道路の状況 前面道路 高低位置",
			"標準地 接面道路の状況 前面道路 道路幅員",
			"標準地 接面道路の状況 前面道路 舗装状況",
			"標準地 接面道路の状況 前面道路 道路種別",
			"標準地 接面道路の状況 側道方位",
			"標準地 接面道路の状況 側道等接面状況",
			"標準地 供給処理施設 水道",
			"標準地 供給処理施設 ガス",
			"標準地 供給処理施設 下水道",
			"標準地 交通施設の状況 交通施設",
			"標準地 交通施設の状況 距離",
			"標準地 交通施設の状況 近接区分",
			"標準地 法令上の規制等 区域区分",
			"標準地 法令上の規制等 用途地域",
			"標準地 法令上の規制等 指定建蔽率",
			"標準地 法令上の規制等 指定容積率",
			"標準地 法令上の規制等 防火地域",
			"標準地 法令上の規制等 森林法",
			"標準地 法令上の規制等 自然公園法",
			"標準地 法令上の規制等 その他 その他地域地区等1",
			"標準地 法令上の規制等 その他 その他地域地区等2",
			"標準地 法令上の規制等 その他 その他地域地区等3",
			"標準地 法令上の規制等 その他 高度地区1 種",
			"標準地 法令上の規制等 その他 高度地区1 高度区分",
			"標準地 法令上の規制等 その他 高度地区1 高度",
			"標準地 法令上の規制等 その他 高度地区2 種",
			"標準地 法令上の規制等 その他 高度地区2 高度区分",
			"標準地 法令上の規制等 その他 高度地区2 高度",
			"標準地 法令上の規制等 その他 基準建蔽率",
			"標準地 法令上の規制等 その他 基準容積率",
			"標準地 法令上の規制等 自然環境等コード1",
			"標準地 法令上の規制等 自然環境等コード2",
			"標準地 法令上の規制等 自然環境等コード3",
			"標準地 法令上の規制等 自然環境等文言",
			"鑑定評価手法の適用 取引事例比較法比準価格",
			"鑑定評価手法の適用 控除法 控除後価格",
			"鑑定評価手法の適用 収益還元法 収益価格",
			"鑑定評価手法の適用 原価法 積算価格",
			"鑑定評価手法の適用 開発法 開発法による価格",
			"比準価格算定内訳事例a 取引価格",
			"比準価格算定内訳事例a 推定価格",
			"比準価格算定内訳事例a 標準価格",
			"比準価格算定内訳事例a 査定価格",
			"比準価格算定内訳事例b 取引価格",
			"比準価格算定内訳事例b 推定価格",
			"比準価格算定内訳事例b 標準価格",
			"比準価格算定内訳事例b 査定価格",
			"比準価格算定内訳事例c 取引価格",
			"比準価格算定内訳事例c 推定価格",
			"比準価格算定内訳事例c 標準価格",
			"比準価格算定内訳事例c 査定価格",
			"比準価格算定内訳事例d 取引価格",
			"比準価格算定内訳事例d 推定価格",
			"比準価格算定内訳事例d 標準価格",
			"比準価格算定内訳事例d 査定価格",
			"比準価格算定内訳事例e 取引価格",
			"比準価格算定内訳事例e 推定価格",
			"比準価格算定内訳事例e 標準価格",
			"比準価格算定内訳事例e 査定価格",
			"積算価格算定内訳素地の取得価格",
			"積算価格算定内訳造成工事費",
			"積算価格算定内訳再調達原価",
			"収益価格算定内訳総収益",
			"収益価格算定内訳総費用",
			"収益価格算定内訳純収益",
			"収益価格算定内訳建物に帰属する純収益",
			"収益価格算定内訳土地に帰属する純収益",
			"収益価格算定内訳未収入期間修正後の純収益",
			"収益価格算定内訳還元利回り",
			"開発法価格算定内訳 収入の現価の総和",
			"開発法価格算定内訳 支出の現価の総和",
			"開発法価格算定内訳 投下資本収益率",
			"開発法価格算定内訳 販売単価(住宅)",
			"開発法価格算定内訳 分譲可能床面積",
			"開発法価格算定内訳 建築工事費",
			"開発法価格算定内訳 延床面積",
			"公示価格",
			"変動率",
			"緯度",
			"経度",
		],
	},
	XPT001: {
		id: "XPT001",
		methodName: "xpt001",
		alias: "getRealEstatePricePoints",
		path: "/XPT001",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xpt001/",
		category: "価格情報",
		nameJa: "不動産価格（取引価格・成約価格）情報のポイント (点) API",
		summaryEn: "Get real estate price point vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
			{ name: "from", inputName: "from", kind: "yearQuarter", required: true, multiple: false, description: "取引時期From" },
			{ name: "to", inputName: "to", kind: "yearQuarter", required: true, multiple: false, description: "取引時期To" },
			{ name: "priceClassification", inputName: "priceClassification", kind: "priceClassification", required: false, multiple: false, description: "価格情報区分コード" },
			{ name: "landTypeCode", inputName: "landTypeCode", kind: "landTypeCode", required: false, multiple: true, description: "種類コード" },
		],
		responseFields: [
			"price_information_category_name_ja",
			"district_code",
			"city_code",
			"prefecture_name_ja",
			"city_name_ja",
			"district_name_ja",
			"u_transaction_price_total_ja",
			"u_unit_price_per_tsubo_ja",
			"floor_plan_name_ja",
			"u_area_ja",
			"u_transaction_price_unit_price_square_meter_ja",
			"land_shape_name_ja",
			"u_land_frontage_ja",
			"u_building_total_floor_area_ja",
			"u_construction_year_ja",
			"building_structure_name_ja",
			"land_use_name_ja",
			"future_use_purpose_name_ja",
			"front_road_azimuth_name_ja",
			"front_road_type_name_ja",
			"u_front_road_width_ja",
			"u_building_coverage_ratio_ja",
			"u_floor_area_ratio_ja",
			"point_in_time_name_ja",
			"remark_renovation_name_ja",
			"remark_name_ja",
			"land_type_name_ja",
			"use_category_name_ja",
			"building_use_name_ja",
		],
	},
	XPT002: {
		id: "XPT002",
		methodName: "xpt002",
		alias: "getLandPricePoints",
		path: "/XPT002",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xpt002/",
		category: "価格情報",
		nameJa: "地価公示・地価調査のポイント (点) API",
		summaryEn: "Get official land price point vector tile data.",
		kind: "tile",
		minZoom: 13,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
			{ name: "year", inputName: "year", kind: "year", required: true, multiple: false, description: "対象年" },
			{ name: "priceClassification", inputName: "priceClassification", kind: "landPriceClassification", required: false, multiple: false, description: "地価情報区分コード" },
			{ name: "useCategoryCode", inputName: "useCategoryCode", kind: "appraisalDivisionCode", required: false, multiple: true, description: "用途区分コード" },
		],
		responseFields: [
			"point_id",
			"target_year_name_ja",
			"land_price_type",
			"prefecture_code",
			"prefecture_name_ja",
			"city_code",
			"use_category_name_ja",
			"standard_lot_number_ja",
			"city_county_name_ja",
			"ward_town_village_name_ja",
			"place_name_ja",
			"residence_display_name_ja",
			"location_number_ja",
			"u_current_years_price_ja",
			"last_years_price",
			"year_on_year_change_rate",
			"u_cadastral_ja",
			"frontage_ratio",
			"depth_ratio",
			"building_structure_name_ja",
			"u_ground_hierarchy_ja",
			"u_underground_hierarchy_ja",
			"front_road_name_ja",
			"front_road_azimuth_name_ja",
			"front_road_width",
			"front_road_pavement_condition",
			"side_road_azimuth_name_ja",
			"side_road_name_ja",
			"gas_supply_availability",
			"water_supply_availability",
			"sewer_supply_availability",
			"nearest_station_name_ja",
			"proximity_to_transportation_facilitites",
			"u_road_distance_to_nearest_station_name_ja",
			"usage_status_name_ja",
			"current_usage_status_of_surrounding_land_name_ja",
			"area_division_name_ja",
			"regulations_use_category_name_ja",
			"regulations_altitude_district_name_ja",
			"regulations_fireproof_name_ja",
			"u_regulations_building_coverage_ratio_ja",
			"u_regulations_floor_area_ratio_ja",
			"regulations_forest_law_name_ja",
			"regulations_park_law_name_ja",
			"pause_flag",
			"usage_category_name_ja",
			"location",
			"shape",
			"front_road_condition",
			"side_road_condition",
			"park_forest_law",
		],
	},
	XKT001: {
		id: "XKT001",
		methodName: "xkt001",
		alias: "getUrbanPlanningAreas",
		path: "/XKT001",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt001/",
		category: "都市計画情報",
		nameJa: "都市計画決定GISデータ（都市計画区域/区域区分）API",
		summaryEn: "Get urban planning area and area classification vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"prefecture",
			"city_code",
			"city_name",
			"kubun_id",
			"decision_date",
			"decision_classification",
			"decision_maker",
			"notice_number",
			"area_classification_ja",
			"first_decision_date",
			"notice_number_s",
		],
	},
	XKT002: {
		id: "XKT002",
		methodName: "xkt002",
		alias: "getUseDistricts",
		path: "/XKT002",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt002/",
		category: "都市計画情報",
		nameJa: "都市計画決定GISデータ（用途地域）API",
		summaryEn: "Get land use district vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"youto_id",
			"prefecture",
			"city_code",
			"city_name",
			"decision_date",
			"decision_classification",
			"decision_maker",
			"notice_number",
			"use_area_ja",
			"u_floor_area_ratio_ja",
			"u_building_coverage_ratio_ja",
			"first_decision_date",
			"notice_number_s",
		],
	},
	XKT003: {
		id: "XKT003",
		methodName: "xkt003",
		alias: "getLocationNormalizationPlans",
		path: "/XKT003",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt003/",
		category: "都市計画情報",
		nameJa: "都市計画決定GISデータ（立地適正化計画）API",
		summaryEn: "Get location normalization plan vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"prefecture",
			"city_code",
			"city_name",
			"decision_date",
			"decision_classification",
			"decision_maker",
			"notice_number",
			"kubun_id",
			"kubun_name_ja",
			"area_classification_ja",
			"first_decision_date",
			"notice_number_s",
		],
	},
	XKT004: {
		id: "XKT004",
		methodName: "xkt004",
		alias: "getElementarySchoolDistricts",
		path: "/XKT004",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt004/",
		category: "周辺施設情報",
		nameJa: "国土数値情報（小学校区）API",
		summaryEn: "Get elementary school district vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
			{ name: "administrativeAreaCode", inputName: "administrativeAreaCode", kind: "administrativeAreaCode", required: false, multiple: true, description: "行政区域コード" },
		],
		responseFields: [
			"A27_001",
			"A27_002",
			"A27_003",
			"A27_004_ja",
			"A27_005",
		],
	},
	XKT005: {
		id: "XKT005",
		methodName: "xkt005",
		alias: "getJuniorHighSchoolDistricts",
		path: "/XKT005",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt005/",
		category: "周辺施設情報",
		nameJa: "国土数値情報（中学校区）API",
		summaryEn: "Get junior high school district vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
			{ name: "administrativeAreaCode", inputName: "administrativeAreaCode", kind: "administrativeAreaCode", required: false, multiple: true, description: "行政区域コード" },
		],
		responseFields: [
			"A32_001",
			"A32_002",
			"A32_003",
			"A32_004_ja",
			"A32_005",
		],
	},
	XKT006: {
		id: "XKT006",
		methodName: "xkt006",
		alias: "getSchools",
		path: "/XKT006",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt006/",
		category: "周辺施設情報",
		nameJa: "国土数値情報（学校）API",
		summaryEn: "Get school vector tile data.",
		kind: "tile",
		minZoom: 13,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"P29_001",
			"P29_002",
			"P29_003",
			"P29_003_name_ja",
			"P29_004_ja",
			"P29_005_ja",
			"P29_006",
			"P29_007",
			"P29_008",
			"P29_009_ja",
		],
	},
	XKT007: {
		id: "XKT007",
		methodName: "xkt007",
		alias: "getPreschools",
		path: "/XKT007",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt007/",
		category: "周辺施設情報",
		nameJa: "国土数値情報（保育園・幼稚園等）API",
		summaryEn: "Get preschool and kindergarten vector tile data.",
		kind: "tile",
		minZoom: 13,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"administrativeAreaCode",
			"preSchoolName_ja",
			"schoolCode",
			"schoolClassCode",
			"schoolClassCode_name_ja",
			"location_ja",
			"administratorCode",
			"closeSchoolCode",
		],
	},
	XKT010: {
		id: "XKT010",
		methodName: "xkt010",
		alias: "getMedicalFacilities",
		path: "/XKT010",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt010/",
		category: "周辺施設情報",
		nameJa: "国土数値情報（医療機関）API",
		summaryEn: "Get medical facility vector tile data.",
		kind: "tile",
		minZoom: 13,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"P04_001",
			"P04_001_name_ja",
			"P04_002_ja",
			"P04_003_ja",
			"P04_004",
			"P04_005",
			"P04_006",
			"P04_007",
			"P04_008",
			"P04_009",
			"P04_010",
			"medical_subject_ja",
		],
	},
	XKT011: {
		id: "XKT011",
		methodName: "xkt011",
		alias: "getWelfareFacilities",
		path: "/XKT011",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt011/",
		category: "周辺施設情報",
		nameJa: "国土数値情報（福祉施設）API",
		summaryEn: "Get welfare facility vector tile data.",
		kind: "tile",
		minZoom: 13,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
			{ name: "administrativeAreaCode", inputName: "administrativeAreaCode", kind: "administrativeAreaCode", required: false, multiple: true, description: "行政区域コード" },
			{ name: "welfareFacilityClassCode", inputName: "welfareFacilityClassCode", kind: "stringCode", required: false, multiple: true, description: "福祉施設大分類コード" },
			{ name: "welfareFacilityMiddleClassCode", inputName: "welfareFacilityMiddleClassCode", kind: "stringCode", required: false, multiple: true, description: "福祉施設中分類コード" },
			{ name: "welfareFacilityMinorClassCode", inputName: "welfareFacilityMinorClassCode", kind: "stringCode", required: false, multiple: true, description: "福祉施設小分類コード" },
		],
		responseFields: [
			"P14_001",
			"P14_002",
			"P14_003",
			"P14_004_ja",
			"P14_005",
			"P14_005_name_ja",
			"P14_006",
			"P14_006_name_ja",
			"P14_007",
			"P14_008_ja",
			"P14_009",
			"P14_010",
		],
	},
	XKT013: {
		id: "XKT013",
		methodName: "xkt013",
		alias: "getFuturePopulationMeshes",
		path: "/XKT013",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt013/",
		category: "人口情報等",
		nameJa: "国土数値情報（将来推計人口250mメッシュ）API",
		summaryEn: "Get future population 250m mesh vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"MESH_ID",
			"SHICODE",
			"PTN_20XX",
			"HITOKU20XX",
			"GASSAN20XX",
			"PT00_20XX",
			"PT01_20XX",
			"PT02_20XX",
			"PT03_20XX",
			"PT04_20XX",
			"PT05_20XX",
			"PT06_20XX",
			"PT07_20XX",
			"PT08_20XX",
			"PT09_20XX",
			"PT10_20XX",
			"PT11_20XX",
			"PT12_20XX",
			"PT13_20XX",
			"PT14_20XX",
			"PT15_20XX",
			"PT16_20XX",
			"PT17_20XX",
			"PT18_20XX",
			"PT19_20XX",
			"PT20_20XX",
			"PTA_20XX",
			"PTB_20XX",
			"PTC_20XX",
			"PTD_20XX",
			"PTE_20XX",
			"RTA_20XX",
			"RTB_20XX",
			"RTC_20XX",
			"RTD_20XX",
			"RTE_20XX",
		],
	},
	XKT014: {
		id: "XKT014",
		methodName: "xkt014",
		alias: "getFirePreventionDistricts",
		path: "/XKT014",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt014/",
		category: "都市計画情報",
		nameJa: "都市計画決定GISデータ（防火・準防火地域）API",
		summaryEn: "Get fire prevention district vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"fire_prevention_ja",
			"kubun_id",
			"prefecture",
			"city_code",
			"city_name",
			"decision_date",
			"decision_classification",
			"decision_maker",
			"notice_number",
			"first_decision_date",
			"notice_number_s",
		],
	},
	XKT015: {
		id: "XKT015",
		methodName: "xkt015",
		alias: "getStationPassengerCounts",
		path: "/XKT015",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt015/",
		category: "人口情報等",
		nameJa: "国土数値情報（駅別乗降客数）API",
		summaryEn: "Get station passenger count vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"S12_001_ja",
			"S12_001c",
			"S12_001g",
			"S12_002_ja",
			"S12_003_ja",
			"S12_004",
			"S12_005",
			"S12_006",
			"S12_007",
			"S12_008",
			"S12_009",
			"S12_010",
			"S12_011",
			"S12_012",
			"S12_013",
			"S12_014",
			"S12_015",
			"S12_016",
			"S12_017",
			"S12_018",
			"S12_019",
			"S12_020",
			"S12_021",
			"S12_022",
			"S12_023",
			"S12_024",
			"S12_025",
			"S12_026",
			"S12_027",
			"S12_028",
			"S12_029",
			"S12_030",
			"S12_031",
			"S12_032",
			"S12_033",
			"S12_034",
			"S12_035",
			"S12_036",
			"S12_037",
			"S12_038",
			"S12_039",
			"S12_040",
			"S12_041",
			"S12_042",
			"S12_043",
			"S12_044",
			"S12_045",
			"S12_046",
			"S12_047",
			"S12_048",
			"S12_049",
			"S12_050",
			"S12_051",
			"S12_052",
			"S12_053",
			"S12_054",
			"S12_055",
			"S12_056",
			"S12_057",
		],
	},
	XKT016: {
		id: "XKT016",
		methodName: "xkt016",
		alias: "getDisasterRiskAreas",
		path: "/XKT016",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt016/",
		category: "防災情報",
		nameJa: "国土数値情報（災害危険区域）API",
		summaryEn: "Get disaster risk area vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
			{ name: "administrativeAreaCode", inputName: "administrativeAreaCode", kind: "administrativeAreaCode", required: false, multiple: true, description: "代表行政コード" },
		],
		responseFields: [
			"A48_001",
			"A48_002",
			"A48_003",
			"A48_004",
			"A48_005_ja",
			"A48_006",
			"A48_007",
			"A48_007_name_ja",
			"A48_008_ja",
			"A48_009",
			"A48_010",
			"A48_011",
			"A48_012",
			"A48_013",
			"A48_014",
		],
	},
	XKT017: {
		id: "XKT017",
		methodName: "xkt017",
		alias: "getLibraries",
		path: "/XKT017",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt017/",
		category: "周辺施設情報",
		nameJa: "国土数値情報（図書館）API",
		summaryEn: "Get library vector tile data.",
		kind: "tile",
		minZoom: 13,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
			{ name: "administrativeAreaCode", inputName: "administrativeAreaCode", kind: "administrativeAreaCode", required: false, multiple: true, description: "行政区域コード" },
		],
		responseFields: [
			"P27_001",
			"P27_002",
			"P27_003",
			"P27_003_name_ja",
			"P27_004",
			"P27_004_name_ja",
			"P27_005_ja",
			"P27_006_ja",
			"P27_007",
			"P27_008",
			"P27_009",
		],
	},
	XKT018: {
		id: "XKT018",
		methodName: "xkt018",
		alias: "getMunicipalOffices",
		path: "/XKT018",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt018/",
		category: "周辺施設情報",
		nameJa: "国土数値情報（市区町村役場及び集会施設等）API",
		summaryEn: "Get municipal office and assembly facility vector tile data.",
		kind: "tile",
		minZoom: 13,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"P05_001",
			"P05_002",
			"P05_002_name_ja",
			"P05_003_ja",
			"P05_004_ja",
		],
	},
	XKT019: {
		id: "XKT019",
		methodName: "xkt019",
		alias: "getNaturalParks",
		path: "/XKT019",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt019/",
		category: "周辺施設情報",
		nameJa: "国土数値情報（自然公園地域）API",
		summaryEn: "Get natural park area vector tile data.",
		kind: "tile",
		minZoom: 9,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
			{ name: "prefectureCode", inputName: "prefectureCode", kind: "prefectureCode", required: false, multiple: true, description: "都道府県コード" },
			{ name: "districtCode", inputName: "districtCode", kind: "stringCode", required: false, multiple: true, description: "地区コード" },
		],
		responseFields: [
			"OBJECTID",
			"PREFEC_CD",
			"AREA_CD",
			"CTV_NAME",
			"FIS_YEAR",
			"THEMA_NO",
			"LAYER_NO",
			"AREA_SIZE",
			"IOSIDE_DIV",
			"REMARK_STR",
			"Shape_Leng",
			"Shape_Area",
			"OBJ_NAME_ja",
		],
	},
	XKT020: {
		id: "XKT020",
		methodName: "xkt020",
		alias: "getLargeScaleEmbankments",
		path: "/XKT020",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt020/",
		category: "地形情報",
		nameJa: "国土数値情報（大規模盛土造成地マップ）API",
		summaryEn: "Get large-scale embankment map vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"embankment_classification",
			"prefecture_code",
			"prefecture_name",
			"city_code",
			"city_name",
			"embankment_number",
		],
	},
	XKT021: {
		id: "XKT021",
		methodName: "xkt021",
		alias: "getLandslidePreventionAreas",
		path: "/XKT021",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt021/",
		category: "防災情報",
		nameJa: "国土数値情報（地すべり防止地区）API",
		summaryEn: "Get landslide prevention district vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
			{ name: "prefectureCode", inputName: "prefectureCode", kind: "prefectureCode", required: false, multiple: true, description: "都道府県コード" },
			{ name: "administrativeAreaCode", inputName: "administrativeAreaCode", kind: "administrativeAreaCode", required: false, multiple: true, description: "行政コード" },
		],
		responseFields: [
			"prefecture_code",
			"group_code",
			"city_name",
			"region_name",
			"address",
			"notice_date",
			"notice_number",
			"landslide_area",
			"charge_ministry_code",
			"prefecture_name",
			"charge_ministry_name",
		],
	},
	XKT022: {
		id: "XKT022",
		methodName: "xkt022",
		alias: "getSteepSlopeHazardAreas",
		path: "/XKT022",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt022/",
		category: "防災情報",
		nameJa: "国土数値情報（急傾斜地崩壊危険区域）API",
		summaryEn: "Get steep slope hazard area vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
			{ name: "prefectureCode", inputName: "prefectureCode", kind: "prefectureCode", required: false, multiple: true, description: "都道府県コード" },
			{ name: "administrativeAreaCode", inputName: "administrativeAreaCode", kind: "administrativeAreaCode", required: false, multiple: true, description: "行政コード" },
		],
		responseFields: [
			"prefecture_code",
			"group_code",
			"city_name",
			"region_name",
			"address",
			"public_notice_date",
			"public_notice_number",
			"landslide_area",
			"prefecture_name",
		],
	},
	XKT023: {
		id: "XKT023",
		methodName: "xkt023",
		alias: "getDistrictPlans",
		path: "/XKT023",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt023/",
		category: "都市計画情報",
		nameJa: "都市計画決定GISデータ（地区計画）API",
		summaryEn: "Get district plan vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"plan_name",
			"plan_type_ja",
			"kubun_id",
			"group_code",
			"decision_date",
			"decision_type_ja",
			"decision_maker",
			"notice_number",
			"prefecture",
			"city_name",
			"first_decision_date",
			"notice_number_s",
		],
	},
	XKT024: {
		id: "XKT024",
		methodName: "xkt024",
		alias: "getHighIntensityUseDistricts",
		path: "/XKT024",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt024/",
		category: "都市計画情報",
		nameJa: "都市計画決定GISデータ（高度利用地区）API",
		summaryEn: "Get high-intensity use district vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"advanced_name",
			"advanced_type_ja",
			"kubun_id",
			"group_code",
			"decision_date",
			"decision_type_ja",
			"decision_maker",
			"notice_number",
			"prefecture",
			"city_name",
			"first_decision_date",
			"notice_number_s",
		],
	},
	XKT025: {
		id: "XKT025",
		methodName: "xkt025",
		alias: "getLiquefactionTendencyAreas",
		path: "/XKT025",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt025/",
		category: "防災情報",
		nameJa: "国土交通省都市局（地形区分に基づく液状化の発生傾向図）API",
		summaryEn: "Get liquefaction tendency area vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"mesh_code",
			"topographic_classification_code",
			"topographic_classification_name_ja",
			"liquefaction_tendency_level",
			"note",
		],
	},
	XKT026: {
		id: "XKT026",
		methodName: "xkt026",
		alias: "getFloodInundationAreas",
		path: "/XKT026",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt026/",
		category: "防災情報",
		nameJa: "国土数値情報（洪水浸水想定区域（想定最大規模））API",
		summaryEn: "Get flood inundation assumed area vector tile data.",
		kind: "tile",
		minZoom: 14,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"A31a_201",
			"A31a_202",
			"A31a_203",
			"A31a_204",
			"A31a_205",
		],
	},
	XKT027: {
		id: "XKT027",
		methodName: "xkt027",
		alias: "getStormSurgeInundationAreas",
		path: "/XKT027",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt027/",
		category: "防災情報",
		nameJa: "国土数値情報（高潮浸水想定区域）API",
		summaryEn: "Get storm surge inundation assumed area vector tile data.",
		kind: "tile",
		minZoom: 13,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"A49_001",
			"A49_002",
			"A49_003",
			"target_year",
		],
	},
	XKT028: {
		id: "XKT028",
		methodName: "xkt028",
		alias: "getTsunamiInundationAreas",
		path: "/XKT028",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt028/",
		category: "防災情報",
		nameJa: "国土数値情報（津波浸水想定）API",
		summaryEn: "Get tsunami inundation assumed area vector tile data.",
		kind: "tile",
		minZoom: 14,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"A40_001",
			"A40_002",
			"A40_003",
			"target_year",
		],
	},
	XKT029: {
		id: "XKT029",
		methodName: "xkt029",
		alias: "getSedimentDisasterHazardAreas",
		path: "/XKT029",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt029/",
		category: "防災情報",
		nameJa: "国土数値情報（土砂災害警戒区域）API",
		summaryEn: "Get sediment disaster hazard area vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"A33_001",
			"A33_002",
			"A33_003",
			"A33_004",
			"A33_005",
			"A33_006",
			"A33_007",
			"A33_008",
		],
	},
	XKT030: {
		id: "XKT030",
		methodName: "xkt030",
		alias: "getUrbanPlanningRoads",
		path: "/XKT030",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt030/",
		category: "都市計画情報",
		nameJa: "都市計画決定GISデータ（都市計画道路）API",
		summaryEn: "Get urban planning road vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"planning_road_ja",
			"kubun_id",
			"prefecture",
			"city_code",
			"city_name",
			"first_decision_date",
			"decision_date",
			"decision_type_ja",
			"decision_maker",
			"notice_number_s",
			"notice_number",
		],
	},
	XKT031: {
		id: "XKT031",
		methodName: "xkt031",
		alias: "getDenselyInhabitedDistricts",
		path: "/XKT031",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xkt031/",
		category: "人口情報等",
		nameJa: "国土数値情報（人口集中地区）API",
		summaryEn: "Get densely inhabited district vector tile data.",
		kind: "tile",
		minZoom: 9,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
			{ name: "administrativeAreaCode", inputName: "administrativeAreaCode", kind: "administrativeAreaCode", required: false, multiple: true, description: "行政区域コード" },
		],
		responseFields: [
			"A16_001",
			"A16_002",
			"A16_003",
			"A16_004",
			"A16_005",
			"A16_006",
			"A16_007",
			"A16_008",
			"A16_009",
			"A16_010",
			"A16_011",
			"A16_012",
			"A16_013",
			"A16_014",
		],
	},
	XGT001: {
		id: "XGT001",
		methodName: "xgt001",
		alias: "getEmergencyEvacuationSites",
		path: "/XGT001",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xgt001/",
		category: "防災情報",
		nameJa: "国土地理院GISデータ（指定緊急避難場所）API",
		summaryEn: "Get designated emergency evacuation site vector tile data.",
		kind: "tile",
		minZoom: 11,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
		],
		responseFields: [
			"common_id",
			"prefecture_and_city",
			"facility_name_ja",
			"address_ja",
			"flood_flag",
			"landslide_flag",
			"high_tide_flag",
			"earthquake_flag",
			"tsunami_flag",
			"large_fire_flag",
			"inland_flooding_flag",
			"volcanic_phenomenon_flag",
			"same_address_flag",
			"remarks",
		],
	},
	XST001: {
		id: "XST001",
		methodName: "xst001",
		alias: "getDisasterHistory",
		path: "/XST001",
		manualUrl: "https://www.reinfolib.mlit.go.jp/help/apiManual/xst001/",
		category: "防災情報",
		nameJa: "国土調査（災害履歴）API",
		summaryEn: "Get disaster history vector tile data.",
		kind: "tile",
		minZoom: 9,
		maxZoom: 15,
		params: [
			{ name: "response_format", inputName: "responseFormat", kind: "responseFormat", required: true, multiple: false, description: "応答形式" },
			{ name: "z", inputName: "z", kind: "tileInteger", required: true, multiple: false, description: "ズームレベル（縮尺）" },
			{ name: "x", inputName: "x", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のX値" },
			{ name: "y", inputName: "y", kind: "tileInteger", required: true, multiple: false, description: "タイル座標のY値" },
			{ name: "disastertype_code", inputName: "disastertypeCode", kind: "stringCode", required: false, multiple: true, description: "災害分類コード" },
		],
		responseFields: [
			"disastertype_code",
			"disaster_name_ja",
			"disaster_date",
			"disaster_source",
		],
	},
} as const satisfies Record<string, EndpointDefinition>;

export type EndpointId = keyof typeof endpoints;

export const endpointIds = Object.keys(endpoints) as EndpointId[];

export const endpointAliases = {
	getRealEstatePrices: "XIT001",
	getMunicipalities: "XIT002",
	getAppraisalReports: "XCT001",
	getRealEstatePricePoints: "XPT001",
	getLandPricePoints: "XPT002",
	getUrbanPlanningAreas: "XKT001",
	getUseDistricts: "XKT002",
	getLocationNormalizationPlans: "XKT003",
	getElementarySchoolDistricts: "XKT004",
	getJuniorHighSchoolDistricts: "XKT005",
	getSchools: "XKT006",
	getPreschools: "XKT007",
	getMedicalFacilities: "XKT010",
	getWelfareFacilities: "XKT011",
	getFuturePopulationMeshes: "XKT013",
	getFirePreventionDistricts: "XKT014",
	getStationPassengerCounts: "XKT015",
	getDisasterRiskAreas: "XKT016",
	getLibraries: "XKT017",
	getMunicipalOffices: "XKT018",
	getNaturalParks: "XKT019",
	getLargeScaleEmbankments: "XKT020",
	getLandslidePreventionAreas: "XKT021",
	getSteepSlopeHazardAreas: "XKT022",
	getDistrictPlans: "XKT023",
	getHighIntensityUseDistricts: "XKT024",
	getLiquefactionTendencyAreas: "XKT025",
	getFloodInundationAreas: "XKT026",
	getStormSurgeInundationAreas: "XKT027",
	getTsunamiInundationAreas: "XKT028",
	getSedimentDisasterHazardAreas: "XKT029",
	getUrbanPlanningRoads: "XKT030",
	getDenselyInhabitedDistricts: "XKT031",
	getEmergencyEvacuationSites: "XGT001",
	getDisasterHistory: "XST001",
} as const;
